# training related
seed: 2024
num_workers: 1
ngpu: 1
batch_type: unsorted
batch_size: 4
accum_grad: 1
max_epoch: 20
log_interval: 100
keep_nbest_models: 10
use_amp: false
multiple_iterator: false

optim: adamw
optim_conf:
    lr: 0.0001
    weight_decay: 0.000001
scheduler: steplr
scheduler_conf:
    step_size: 1000

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 27
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_ratio_range:
    - 0.
    - 0.05
    num_time_mask: 5